version: "3.8"

services:
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:sha-23150b6
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_HOST=db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-secret}
      - SALT=${SALT:-salt}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  clean-data:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m src.data.clean_data
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy

  preprocess:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m src.core.embedding
    depends_on:
      clean-data:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/indexes/faiss_index.faiss"]
      interval: 5s
      retries: 5
      start_period: 10s

  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      preprocess:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

volumes:
  database_data:
    driver: local
